#FROM golang:1.17-alpine
#
#WORKDIR /app
##
##COPY /go.mod ./go.mod
##COPY /go.sum ./go.sum
##
##RUN go mod download
#
#COPY /project/modals/ ./project/modals/
#COPY project/cmd/topic/topic.go ./project/cmd/topic/topic.go
##COPY /cmd/kafka_consumer/customer.go ./cmd/kafka_consumer/customer.go
#
#RUN go build -o /topic ./project/cmd/topic/topic.go
##RUN go build -o /customer ./cmd/kafka_consumer/customer.go
#
#CMD ["/topic"]
##CMD ["/customer"] waiting