version: '3'
services:
  my-mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017

  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=driver
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  my-location-service:
    build:
      context: .
      dockerfile: internal/location/Dockerfile
    ports:
      - 8828:8828
    depends_on:
      postgres-container:
         condition: service_healthy

  my-driver-service:
    build:
      context: .
      dockerfile: internal/driver/Dockerfile
    ports:
      - 5395:5395
    depends_on:
      - my-mongodb

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
