version: '3'
services:
  my-mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017

  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=driver
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  my-location-service:
    build:
      context: .
      dockerfile: internal/location/Dockerfile
    ports:
      - 8828:8828
    depends_on:
      postgres-container:
         condition: service_healthy

  my-driver-service:
    build:
      context: .
      dockerfile: internal/driver/Dockerfile
    ports:
      - 5395:5395
    depends_on:
      - my-mongodb

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one

#  zookeeper-1:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_PEER_PORT: 2888
#      ZOOKEEPER_LEADER_PORT: 3888
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888"
#    ports:
#      - 22181:2181
#    volumes:
#      - ./data/zoo1/data:/var/lib/zookeeper/data
#      - ./data/zoo1/log:/var/lib/zookeeper/log
#
#  kafka-1:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper-1
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_BROKER_RACK: Docker
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181/kafka
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_JMX_PORT: 39999
#    volumes:
#      - ./data/kafka1:/var/lib/kafka/data