version: '3'
services:
  my-mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017

  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=driver
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  my-location-service:
    build:
      context: .
      dockerfile: internal/location/Dockerfile
    ports:
      - 8827:8827
    depends_on:
      postgres-container:
         condition: service_healthy

  my-driver-service:
    build:
      context: .
      dockerfile: internal/driver/Dockerfile
    ports:
      - 5394:5394
    depends_on:
      - my-mongodb
