-- +goose Up
-- +goose StatementBegin
CREATE TABLE driver
(
    id          integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lat         integer     NOT NULL,
    lng         integer     NOT NULL,
    name        varchar     NOT NULL,
    auto        varchar     NOT NULL
);
-- +goose StatementEnd
